apiVersion: apps/v1
kind: Deployment
metadata:
  name: coll-3bddc54abf7f44018fab3adc3aaa9655-depl
  labels:
    app: coll-3bddc54abf7f44018fab3adc3aaa9655
    release: prometheus  # Added label for PodMonitor discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coll-3bddc54abf7f44018fab3adc3aaa9655
      release: prometheus  # Added label for PodMonitor discovery
  template:
    metadata:
      labels:
        app: coll-3bddc54abf7f44018fab3adc3aaa9655
        release: prometheus  # Added label for PodMonitor discovery
    spec:
      containers:
        - name: coll-3bddc54abf7f44018fab3adc3aaa9655
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:coll-3bddc54abf7f44018fab3adc3aaa9655
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              name: http  # Optional for HTTP traffic
            - containerPort: 7070 #same as the deployed code
              name: metrics  # Added port for metrics scraping