apiVersion: v1
kind: Service
metadata:
  name: coll-3bddc54abf7f44018fab3adc3aaa9655-srv
spec:
  selector:
    app: coll-3bddc54abf7f44018fab3adc3aaa9655
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070
  type: ClusterIP